version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo



volumes:
  mongo_data:
